// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1c_jF03BRptoYmC97uH1QtZUZAXxOcoM',
    appId: '1:897983438739:web:1e7bae21e656580760d266',
    messagingSenderId: '897983438739',
    projectId: 'e-commerce-72844',
    authDomain: 'e-commerce-72844.firebaseapp.com',
    storageBucket: 'e-commerce-72844.appspot.com',
    measurementId: 'G-BZC8674BER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBOzkQNDtTUYYoznCFre4ZRdOubbUoVdQ',
    appId: '1:897983438739:android:e55726b8c1ae9aa160d266',
    messagingSenderId: '897983438739',
    projectId: 'e-commerce-72844',
    storageBucket: 'e-commerce-72844.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALLC-qnwe6xL-95812onmKNWEYpdnJrp8',
    appId: '1:897983438739:ios:92e2d38b49145b2760d266',
    messagingSenderId: '897983438739',
    projectId: 'e-commerce-72844',
    storageBucket: 'e-commerce-72844.appspot.com',
    iosClientId: '897983438739-m645l3v07hkca1d2123utubhm417iqv2.apps.googleusercontent.com',
    iosBundleId: 'mehani.sim.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALLC-qnwe6xL-95812onmKNWEYpdnJrp8',
    appId: '1:897983438739:ios:92e2d38b49145b2760d266',
    messagingSenderId: '897983438739',
    projectId: 'e-commerce-72844',
    storageBucket: 'e-commerce-72844.appspot.com',
    iosClientId: '897983438739-m645l3v07hkca1d2123utubhm417iqv2.apps.googleusercontent.com',
    iosBundleId: 'mehani.sim.eCommerce',
  );
}
